### ISSUE TITLE
Example usage does not work as expected

### ISSUE THREAD

**Issue by jan-polivka** [goadesign/model#491]
Hi, I am trying this program out and I am struggling with the installation according to the instruction.

The following commands

```
go install goa.design/model/cmd/mdl
go install goa.design/model/cmd/stz
```

were a bit tricky to figure out as I wasn't sure where the bins are installed (I am not that experienced with Go) but I eventually found them in ~/go/bin.

However, I am struggling with this one
`mdl serve goa.design/model/examples/basic/model -dir gen`
I switched to ~/go/bin and ran 

`mdl serve goa.design/model/examples/basic/model -dir gen`

but I get the following error
`go: go.mod file not found in current directory or any parent directory; see 'go help modules'`

Is there anything missing in the instructions, perhaps? I am running this in WSL2 - Ubuntu - 22.04.

**Comment by raphael** [comment]
Hello! To setup Go properly the `$GOPATH/bin` directory must be added to `$PATH` (`$GOPATH` defaults to `$HOME/go` if not set explicitly). See https://go.dev/doc/install for more information. This will make it so that `mdl` can be called from anywhere.

For the second error `mdl` needs to be run from within a Go module so from a directory that has a `go.mod` file or that has a parent directory with a `go.mod` file. Creating a `go.mod` file can be done with `go mod init <name of module>`.
